### ISSUE TITLE
[API] fix parse,chunking, generate_qa_docs 

### ISSUE THREAD

**Issue by hongsw** [Auto-RAG/autorag-frontend#3]
[API] fix validate and evaluation api config, set_trial_config

**Comment by vkehfdl1** [comment]
```
# Open the Chat API
curl -X GET http://localhost:5000/projects/{{project_id}}/trials/{{trial_id}}/chat/open

# Close the Chat API
curl -X GET http://localhost:5000/projects/{{project_id}}/trials/{{trial_id}}/chat/close
```

The default port is 8501 for streamlit web. @hongsw

**Comment by hongsw** [comment]
> ```
> # Open the Chat API
> curl -X GET http://localhost:5000/projects/{{project_id}}/trials/{{trial_id}}/chat/open
> 
> # Close the Chat API
> curl -X GET http://localhost:5000/projects/{{project_id}}/trials/{{trial_id}}/chat/close
> ```
> 
> The default port is 8501 for streamlit web. @hongsw

move to another issue!!
